#!/bin/sh

# Check if in a git directory
git status >/dev/null 2>/dev/null || { echo "Error: Use tool in a git directory"; exit 1; }

# Select current branch
local_branch=$(git branch --format='%(refname:short)' | fzf --prompt "Select a local branch: ")
[[ $local_branch = "" ]] && exit 1

remote_branch=$(git ls-remote --heads origin | cut -f 2 | sed 's|^refs/heads/|origin/|' | fzf --prompt "Select a remote branch to compare to: ")
[[ $remote_branch = "" ]] && exit 1

file_to_compare=$(find . -type f | fzf --prompt "Select a file to compare: ")
[[ $file_to_compare = "" ]] && exit 1

git diff $remote_branch $local_branch -- $file_to_compare
